debug_mode: true

core:
  logging:
    version: 1
    formatters:
      formatter:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
    handlers:
      console:
        class: "logging.StreamHandler"
        level: "DEBUG"
        formatter: "formatter"
        stream: "ext://sys.stderr"
    root:
      level: "DEBUG"
      handlers: ["console"]

adapters:
  # Servers as either urls or paths to python modules (not javascript for now)
  mcp_servers:
    example_server:
      url: "http://localhost:9090/sse"
    git:
      command: uv
      args:
        [
          "--directory",
          "../../mcp-servers/official-servers/src/git",
          "run",
          "mcp-server-git",
        ]
    github:
      command: npx
      args: ["-y", "@modelcontextprotocol/server-github"]
      env:
        GITHUB_PERSONAL_ACCESS_TOKEN: $GITHUB_PERSONAL_ACCESS_TOKEN
    filesystem:
      command: npx
      args: ["-y", "@modelcontextprotocol/server-filesystem", "~/mcp_allowed/"]
